### PR TITLE
Fixing windows container builds

### LINKED ISSUE #31: Container Image Compatibility
I tried to run `gcr.io/k8s-staging-win-svc-proxy/kpng:latest` on a windows node but it failed to extract the image.

This image works fine in linux nodes, I even tried running some random images in windows nodes to make sure **containerd** is working fine. 
Looks like this image is not compatible with Windows.

Kubelet (windows) logs:
```
pod kpng-xtxqc_kube-system(11354247-eaf4-4d38-a3d6-3ccef7924783): ErrImagePull: rpc error: code = Unknown desc = failed to pull and unpack image "gcr.io/k8s-staging-win-svc-proxy/kpng:lat
est": failed to extract layer sha256:78454dbb2bd225e19cfa0bcad7226087c9b44bb23ac1640e8582a916cef0665e: hcsshim::ProcessBaseLayer \\?\C:\ProgramData\containerd\root\io.containerd.snapshott
er.v1.windows\snapshots\57: The system cannot find the path specified.: unknown                                                                                                            

E0203 05:14:47.298055   42308 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kpng-win\" with ErrImagePull: \"rpc error: code = Unknown desc = fa
iled to pull and unpack image \\\"gcr.io/k8s-staging-win-svc-proxy/kpng:latest\\\": failed to extract layer sha256:78454dbb2bd225e19cfa0bcad7226087c9b44bb23ac1640e8582a916cef0665e: hcsshi
m::ProcessBaseLayer \\\\\\\\?\\\\C:\\\\ProgramData\\\\containerd\\\\root\\\\io.containerd.snapshotter.v1.windows\\\\snapshots\\\\57: The system cannot find the path specified.: unknown\""
 pod="kube-system/kpng-xtxqc" podUID=11354247-eaf4-4d38-a3d6-3ccef7924783 
```

### PR DESCRIPTION
**Pull request by marosset**
Signed-off-by: Mark Rossetti <marosset@microsoft.com>

/assign @jayunit100 @daman1807
Fixes https://github.com/kubernetes-sigs/windows-service-proxy/issues/31

### CODE REVIEW

**Comment by marosset** [comment]
I tested this out with `mrosse3/kpng:test` and `mrosse3/kpng:latest` (both pushed from the same execution of the script) and was able to pull both images on Windows nodes

**Comment by jayunit100** [comment]
Thanks mark!!!! Ok looking now

**Comment by aroradaman** [comment]
Thanks @marosset, With the new build script I'm now able to pull the image on the windows node after downgrading buildx to `v0.9.1`.
Let me add this constraint in the README till this -> https://github.com/containerd/containerd/issues/8070 has been fixed.

Also, I ran into this afterward:
`./start-kpng.ps1 : The term './start-kpng.ps1' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try`

Looks like a small issue with the Dockerfile, filling a new issue for the same and I will pick this up.
cc @jayunit100 

/lgtm

**Comment by marosset** [comment]
@daman1807 - what version of containerd do you have on the nodes?
I'm running ` containerd://1.7.0-beta.3` from the GH release and the pod is starting up normally.
In containerd v1.7 we added some paths to `PATH` by default for hostprocess containers.

**Comment by aroradaman** [comment]
Thanks @marosset !

I will update the containerd in the windows node to 1.7.0-beta.3 and test that out.

I altered the working dir and paths in `start-kpng.ps1` to make it work.
https://github.com/kubernetes-sigs/windows-service-proxy/blob/main/Dockerfile.windows#L11

**Comment by aroradaman** [comment]
@marosset I tried with `1.7.0-beta.3` but still, the issue persists. Shall I update the dockerfile here, it works if I update the dockerfile. 
Screenshot 2023-02-10 at 11 40 04 PM

**Comment by marosset** [comment]
Interesting - I've been testing this on Windows Server 2022 nodes. I wonder if there is some difference in behavior with Windows Server 2019 and Windows Server 2022 w.r.t. the paths here. I'll see if i can find something out

**Pull request merged**
